import { Input } from 'components/form/Input'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

const Home: NextPage = () => {
    const [name, setName] = useState<string>('')
    console.log('Name', '===> ', name)
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="grid grid-cols-1 lg:grid-cols-4">
                <Input onChange={setName} name="Correo" type="search" />
            </div>
        </div>
    )
}

export default Home
