import { Button, Input } from 'components/form'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Siglo 21 Restaurant</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Siglo 21 home page</h1>
        </div>
    )
}

export default Home
